name: Deployment Pipeline for develop branch
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    permissions: write-all
    runs-on: windows-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up .NET
      id: setup
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '6.x'
        
    - name: Build .NET solution
      id: build
      run: |
        dotnet build gamevault.sln --configuration Release
        7z a GameVault.zip gamevault/bin
    
    - name: Upload Release Artifact
      id: upload
      uses: actions/upload-release-asset@v1
      with:
        asset_path: GameVault.zip
        asset_name: GameVault.zip
        asset_content_type: application/zip
        upload_url: "https://api.github.com/repos/Phalcode/gamevault-app/releases/tags/unstable"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
