name: Deployment Pipeline for develop branch
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    permissions: write-all
    runs-on: windows-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2
      
    - name: Set up .NET
      id: setup
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '6.x'
        
    - name: Build .NET solution
      id: build
      run: |
        dotnet build gamevault.sln --configuration Release
        7z a GameVault.zip gamevault/bin

    - name: Get release information
      id: release
      run: |
        REPO="Phalcode/gamevault-app"
        TAG="unstable"
        RELEASE=$(curl -s "https://api.github.com/repos/$REPO/releases/tags/$TAG")
        echo "Release URL: $(echo $RELEASE | jq -r .upload_url)" # Ensure jq is installed on your runner
        echo "upload_url=$(echo $RELEASE | jq -r .upload_url | sed 's/{?name,label}//')" >> $GITHUB_ENV
    
    - name: Upload Release Artifact
      id: upload
      uses: actions/upload-release-asset@v1
      with:
        asset_path: GameVault.zip
        asset_name: GameVault.zip
        asset_content_type: application/zip
        upload_url: ${{ env.upload_url }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
